deployment:
- any: ['.github/workflows/*.yml', '!labeler.yml']

project:
- '*.sln'
- '*.proj'

translation:
- 'src/locales/*.resx'

wordlists:
- 'src/locales/*.json'

design:
- 'src/Resources/*.png'

testcase:
- 'Mastermind.Tests/*.cs'
- './**/*Test*.cs'
