deployment:
- any: ['.github/workflows/*.yml', '!labeler.yml']

project:
- any: ['*.sln', '*.proj']

translation:
- any: ['src/locales/*.resx']

wordlists:
- any: ['src/locales/*.json']

design:
- any: ['src/Resources/*.png']

testcase:
- any: ['Mastermind.Tests/*.cs']
