//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lang {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MastermindVariante.locales.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Solution is: {0} ähnelt.
        /// </summary>
        internal static string DebugShowSolution {
            get {
                return ResourceManager.GetString("DebugShowSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Word guessing game ähnelt.
        /// </summary>
        internal static string DescriptiveTitle {
            get {
                return ResourceManager.GetString("DescriptiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string ErrorMessageTitle {
            get {
                return ResourceManager.GetString("ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Planned function not yet implemented ähnelt.
        /// </summary>
        internal static string FutureFeatureMessageText {
            get {
                return ResourceManager.GetString("FutureFeatureMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New feature ähnelt.
        /// </summary>
        internal static string FutureFeatureMessageTitle {
            get {
                return ResourceManager.GetString("FutureFeatureMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End of game.\r\nSolution was:\r\n{0} ähnelt.
        /// </summary>
        internal static string GameEndedMessage {
            get {
                return ResourceManager.GetString("GameEndedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giving up that quick? Really? ähnelt.
        /// </summary>
        internal static string GivingUpQuestion {
            get {
                return ResourceManager.GetString("GivingUpQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stopping game ähnelt.
        /// </summary>
        internal static string GivingUpTitle {
            get {
                return ResourceManager.GetString("GivingUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exact position: {0}, included: {1} ähnelt.
        /// </summary>
        internal static string GuessedWordPointsAsString {
            get {
                return ResourceManager.GetString("GuessedWordPointsAsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        /// </summary>
        internal static string NewGameButtonText {
            get {
                return ResourceManager.GetString("NewGameButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is no running game at the moment. ähnelt.
        /// </summary>
        internal static string NoRunningGameText {
            get {
                return ResourceManager.GetString("NoRunningGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No running game ähnelt.
        /// </summary>
        internal static string NoRunningGameTitle {
            get {
                return ResourceManager.GetString("NoRunningGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Player Name (optional) ähnelt.
        /// </summary>
        internal static string PlayerNamePlaceholder {
            get {
                return ResourceManager.GetString("PlayerNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F2: Open the keyboard,\r\n# = Okay/Submit guessing\r\nF4: Open Statistics ähnelt.
        /// </summary>
        internal static string QuickHelpText {
            get {
                return ResourceManager.GetString("QuickHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please stop the running game first. ähnelt.
        /// </summary>
        internal static string RunningGameMessageText {
            get {
                return ResourceManager.GetString("RunningGameMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Running game ähnelt.
        /// </summary>
        internal static string RunningGameMessageTitle {
            get {
                return ResourceManager.GetString("RunningGameMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Word length ähnelt.
        /// </summary>
        internal static string WordLengthLabelText {
            get {
                return ResourceManager.GetString("WordLengthLabelText", resourceCulture);
            }
        }
    }
}
